### PR TITLE
Fix #943: fix(quality): webhook feedback misses review-goal agent runs

### LINKED ISSUE #943: fix(quality): webhook feedback misses review-goal agent runs
## Summary

Quality metrics webhooks and feedback collection jobs cannot associate human feedback with review-goal agent runs. Feedback is silently attributed to the original create_pr run or lost entirely.

### 1. Webhook find_agent_run misses review-goal runs

`GithubWebhooksController#find_agent_run` (app/controllers/api/github_webhooks_controller.rb:114-123) queries `where(pull_request_number: pr_number)`. Review-goal runs intentionally do NOT set pull_request_number -- they use source_pull_request_number instead (see complete_review_goal_activity.rb:27-29).

So:
- Human reactions (thumbs up/down) on paid-agent review comments find the original create_pr run, not the review-goal run
- Later human reviews (APPROVED/CHANGES_REQUESTED) associate with the create_pr run, not the review run
- Quality feedback on review-goal run output is lost or misattributed

### 2. HumanFeedbackCollectionJob for review goals

`HumanFeedbackCollectionJob` dispatches to `collect_review_reaction_feedback` for review-goal runs (line 28), but the agent run has no pull_request_number set. The reaction collection may not locate PR comments to scrape reactions from.

### find_agent_run enhancement

Add a secondary lookup for review-goal runs:

```ruby
def find_agent_run(pr_number)
  return nil unless @project && pr_number

  run = @project.agent_runs
    .where(pull_request_number: pr_number, status: "completed")
    .order(created_at: :desc)
    .first

  run || @project.agent_runs
    .where(source_pull_request_number: pr_number, goal: "review", status: "completed")
    .order(created_at: :desc)
    .first
end
```

### collect_review_reaction_feedback fix

Ensure `CollectReviewReactionFeedback` uses `source_pull_request_number` when `pull_request_number` is nil for review-goal runs.

## Test plan

- Webhook spec: pull_request_review event on a PR with both create_pr and review runs attributes feedback to the correct run
- HumanFeedbackCollectionJob spec: review-goal run collects reactions from source_pull_request_number

### PR DESCRIPTION
**Pull request by viamin**
## Summary

fix(quality): webhook feedback misses review-goal agent runs

See #943 for context. Paid was unable to auto-generate a description for this PR;
the diff is the authoritative source of truth.

---

Closes #943

### CODE REVIEW

File: app/controllers/api/github_webhooks_controller.rb [hunk 1]
```diff
@@ -116,10 +116,17 @@ def find_agent_run(pr_number)
...
+      # instead of pull_request_number, so fall back to that lookup.
       @project.agent_runs
         .where(pull_request_number: pr_number, status: "completed")
         .order(created_at: :desc)
-        .first
+        .first ||
+        @project.agent_runs
+          .where(source_pull_request_number: pr_number, goal: "review", status: "completed")
+          .order(created_at: :desc)
+          .first
```
Comment (viamin) [inline app/controllers/api/github_webhooks_controller.rb:142]: **Performance nit (low priority):** The existing partial index `idx_agent_runs_unique_active_pr` on `(project_id, source_pull_request_number)` only covers active statuses (`queued`/`pending`/`running`/`paused`). This new query filters `status: "completed"`, so the partial index won't be used — it'll fall back to `index_agent_runs_on_project_id_and_status` and then scan for `source_pull_request_number`.

For the webhook hot-path this is probably fine (low cardinality per project), but if review-goal feedback volume grows, a composite index on `(project_id, source_pull_request_number, status)` would help. Not blocking — just flagging for future consideration.

File: spec/requests/api/github_webhooks_spec.rb [hunk 2]
```diff
@@ -65,6 +65,67 @@ def sign_payload(payload, secret)
...
+          repository: {
+            id: project.github_id,
+            full_name: project.full_name
+          }
+        }
+      end
+
+      it "attributes feedback to the review-goal run, not the create_pr run" do
+        # Create a create_pr run on the same PR to ensure the review run is preferred
+        # when no create_pr run matches
```
Comment (viamin) [inline spec/requests/api/github_webhooks_spec.rb]: The comment says "Create a create_pr run on the same PR to ensure the review run is preferred when no create_pr run matches" but no `create_pr` run is actually created in this test — which is correct behavior (testing the fallback path). The comment is slightly misleading; consider rewording to something like:

```suggestion
        # No create_pr run exists for PR 77, so the fallback to
        # source_pull_request_number should find the review-goal run.
```

File: spec/requests/api/github_webhooks_spec.rb [hunk 3]
```diff
@@ -65,6 +65,67 @@ def sign_payload(payload, secret)
...
+            params: body,
+            headers: {
+              "Content-Type" => "application/json",
+              "X-GitHub-Event" => "pull_request_review",
+              "X-Hub-Signature-256" => signature
+            }
+        }.to change { pr_run.quality_metrics.human.count }.by(1)
+
+        expect(response).to have_http_status(:ok)
+        expect(review_run.quality_metrics.human.count).to eq(0)
```
Comment (viamin) [inline spec/requests/api/github_webhooks_spec.rb:125]: Nice — this correctly verifies that the `pull_request_number` lookup takes priority over the `source_pull_request_number` fallback, matching the `||` ordering in the controller. Good coverage.

File: app/controllers/api/github_webhooks_controller.rb (hunk 1 above)
Comment (viamin) [inline app/controllers/api/github_webhooks_controller.rb:142]: **Scope question:** Issue #943 also calls out a second fix needed in `HumanFeedbackCollectionJob` — specifically that `collect_review_reaction_feedback` should fall back to `source_pull_request_number` when `pull_request_number` is nil for review-goal runs. This PR only addresses the webhook controller half. Is the job fix intentionally deferred to a follow-up PR, or was it missed?

**Review by viamin — COMMENTED** [review]
Clean, well-scoped fix. The fallback lookup logic is correct and the tests cover both the fallback and the priority cases. Two notes below — one performance nit and one scope question about the missing `HumanFeedbackCollectionJob` fix mentioned in #943.

**Comment by viamin** [comment]
## Agent Update

The background task notification is from the earlier failed commit attempt (before I fixed the pre-commit hook). The commit has already succeeded — you can see it in the log at `5d14796b`. No action needed.

File: app/controllers/api/github_webhooks_controller.rb [hunk 4]
```diff
@@ -116,10 +116,23 @@ def find_agent_run(pr_number)
...
       # metrics — mirrors the guard in HumanFeedbackCollectionJob#perform.
+      #
+      # Review-goal runs set source_pull_request_number (the PR they reviewed)
+      # instead of pull_request_number, so fall back to that lookup.
+      # The HumanFeedbackCollectionJob side already handles this via
+      # CollectReviewReactionFeedback, which queries source_pull_request_number
+      # directly for review-goal runs.
+      #
+      # TODO(#943): if review-goal feedback volume grows, consider a composite
+      # index on (project_id, source_pull_request_number, status).
```
Comment (viamin) [inline app/controllers/api/github_webhooks_controller.rb:134]: The TODO is reasonable but worth noting: there's already a partial unique index on `(project_id, source_pull_request_number)` (for active runs). The fallback query here filters on `status: "completed"`, which that index excludes. If this query path gets meaningful traffic, the composite index mentioned here would help. For now the volume is likely low enough that this is fine — just flagging that the existing index won't cover this query.

File: app/controllers/api/github_webhooks_controller.rb [hunk 5]
```diff
@@ -116,10 +116,23 @@ def find_agent_run(pr_number)
...
       @project.agent_runs
         .where(pull_request_number: pr_number, status: "completed")
         .order(created_at: :desc)
-        .first
+        .first ||
+        @project.agent_runs
+          .where(source_pull_request_number: pr_number, goal: "review", status: "completed")
+          .order(created_at: :desc)
+          .first
```
Comment (viamin) [inline app/controllers/api/github_webhooks_controller.rb:142]: Nit: `handle_pull_request` (line 63) and `handle_issue_comment` (line 94-98) also call `find_agent_run`. For merged-PR events, the fallback to review-goal runs seems correct — a merged PR that was reviewed by an agent should still attribute the merge signal. For issue comments on PRs, same logic applies.

Just confirming this was intentional — the fallback applies to all three event types, not just `pull_request_review`. That seems like the right behavior.

File: spec/requests/api/github_webhooks_spec.rb [hunk 6]
```diff
@@ -65,6 +65,67 @@ def sign_payload(payload, secret)
...
+
+        expect {
+          post webhook_url,
+            params: body,
+            headers: {
+              "Content-Type" => "application/json",
+              "X-GitHub-Event" => "pull_request_review",
+              "X-Hub-Signature-256" => signature
+            }
+        }.to change { review_run.quality_metrics.human.count }.by(1)
```
Comment (viamin) [inline spec/requests/api/github_webhooks_spec.rb:104]: Good test — checks that the metric is attributed to the specific `review_run` instance, not just that a metric was created globally. This catches misattribution bugs that the existing test on line 47 (`QualityMetric.human.count`) would miss.

**Review by viamin — COMMENTED** [review]
## Review Summary

Clean, well-scoped fix that addresses #943 correctly. The fallback lookup pattern is sound — primary lookup by `pull_request_number`, then secondary by `source_pull_request_number` + `goal: "review"`. Tests cover both the fallback case and the precedence case.

Two minor observations below, but overall this looks good to merge.

**Comment by viamin** [comment]
## Agent Update

Commit succeeded. Here's a summary of what was addressed:

**Thread 1 (index coverage):** Added a NOTE comment above the TODO clarifying that the existing partial unique index on `(project_id, source_pull_request_number)` covers active runs only and won't help this completed-status query, but volume is low enough that it's fine for now.

**Thread 2 (fallback scope):** Added a method-level comment on `find_agent_run` documenting that the review-goal fallback is intentionally shared by all three event handlers (pull_request_review, pull_request, issue_comment), confirming the reviewer's observation.

**Thread 3 (test quality):** Positive feedback — no action needed.

**Conversation comment:** Agent update was informational — no action needed (commit `5d14796b` already succeeded).

**Review by viamin — COMMENTED** [review]
Generated no new comments. The fallback lookup for review-goal runs via `source_pull_request_number` is correct, properly scoped to `goal: "review"`, and maintains precedence for `pull_request_number` matches. Tests cover both the fallback and precedence scenarios. Comments and TODO are appropriate.
